### ISSUE TITLE
nvcc fatal

### ISSUE THREAD

**Issue by Panxuran** [DeadAt0m/ActiveSparseShifts-PyTorch#8]
Hi! I got '_nvcc fatal : Unsupported gpu architecture 'compute_86'_' when running 'python setup.py install'. Does this module support cuda 11.0?

**Comment by DeadAt0m** [comment]
Yes, it does and even cuda 11.2.
But obviously, you new GPU(Ampere) is not working under cuda 11.0, because it supported since 11.1 version( [proof](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/))

So, please update your cuda toolkit first!
